version: "3"
services:
   Drupal:
     container_name: Drupal_server
     image: drupal:8-apache
     ports:
       - "8090:80"
     volumes:
       - "drupal_data:/var/www/html"
     networks:
       - net
   psql:
     container_name: Drupal_psql
     image: postgres
     environment:
          POSTGRES_PASSWORD: DRUPAL123
     volumes:
       - "$PWD/psql_data:/var/lib/postgresql/data"
     networks:
       - net
volumes:
    drupal_data:
networks:
    net:

