version: "3"
services:
   Jhoomla:
     container_name: Jhoomla_server
     image: jhoomla
     ports:
       - "8091:80"
     volumes:
       - "$PWD/jhoomla_data:/var/www/html"
     environment:
          JHOOMLA_DB_HOST: Jhoomla_mysql
          JHOOMLA_DB_NAME: jhoomla
          JHOOMLA_DB_USER: jhoomla
          JHOOMLA_DB_PASSWORD: jhoomla
     networks:
       - net
   mysql:
     container_name: Jhoomla_mysql
     image: mysql:5.7
     environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: jhoomla
          MYSQL_PASSWORD: jhoomla
          MYSQL_DATABASE: jhoomla
     volumes:
       - "$PWD/mysql_data:/var/lib/mysql"
     networks:
       - net
networks:
    net:

